version: "3"
services:
  minecraft:
    build: .
    image: valderman/minecraft:latest
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "0.0.0.0:25565:25565"
    volumes:
      - /data/minecraft:/data
    environment:
      - OPS=valderman
      - ALLOW=nyson th4m MamegomaBuilds Adlitam Zorando BunnyFiscuit Vaio Niadra
      - HEAP=2G
