version: "3"
services:
  minecraft:
    build: .
    image: valderman/minecraft:latest
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "0.0.0.0:25565:25565"
    volumes:
      - /data/minecraft:/data
