name: build-and-push
on: [push]
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: /usr/bin/buildah bud --isolation=chroot --storage-driver=vfs -t "sebas:5000/minecraft:latest" .
      - run: /usr/bin/buildah push "sebas:5000/minecraft:latest"