name: build-and-push
on: [push]
jobs:
  build-and-push:
    runs-on: [self-hosted, x64]
    steps:
      - uses: actions/checkout@v3
      - run: |
          TAG=$(git rev-parse --short ${{ github.sha }})
          buildah bud --isolation=chroot --storage-driver=vfs -t sebas:5000/minecraft:$TAG .
          buildah push --tls-verify=false sebas:5000/minecraft:$TAG
          if [ "${{ github.ref_name }}" == "master" ] ; then
            buildah tag sebas:5000/minecraft:$TAG sebas:5000/minecraft:latest
            buildah push --tls-verify=false sebas:5000/minecraft:latest
          fi
